export type CountryCode = {
  flag: string;
  label: string;
  code: string;
};

export const COUNTRY_CODES: CountryCode[] = [
  { flag: '🇦🇫', label: 'Afghanistan', code: '+93' },
  { flag: '🇦🇱', label: 'Albania', code: '+355' },
  { flag: '🇩🇿', label: 'Algeria', code: '+213' },
  { flag: '🇦🇸', label: 'American Samoa', code: '+1-684' },
  { flag: '🇦🇩', label: 'Andorra', code: '+376' },
  { flag: '🇦🇴', label: 'Angola', code: '+244' },
  { flag: '🇦🇮', label: 'Anguilla', code: '+1-264' },
  { flag: '🇦🇬', label: 'Antigua & Barbuda', code: '+1-268' },
  { flag: '🇦🇷', label: 'Argentina', code: '+54' },
  { flag: '🇦🇲', label: 'Armenia', code: '+374' },
  { flag: '🇦🇼', label: 'Aruba', code: '+297' },
  { flag: '🇦🇺', label: 'Australia', code: '+61' },
  { flag: '🇦🇹', label: 'Austria', code: '+43' },
  { flag: '🇦🇿', label: 'Azerbaijan', code: '+994' },

  { flag: '🇧🇸', label: 'Bahamas', code: '+1-242' },
  { flag: '🇧🇭', label: 'Bahrain', code: '+973' },
  { flag: '🇧🇩', label: 'Bangladesh', code: '+880' },
  { flag: '🇧🇧', label: 'Barbados', code: '+1-246' },
  { flag: '🇧🇾', label: 'Belarus', code: '+375' },
  { flag: '🇧🇪', label: 'Belgium', code: '+32' },
  { flag: '🇧🇿', label: 'Belize', code: '+501' },
  { flag: '🇧🇯', label: 'Benin', code: '+229' },
  { flag: '🇧🇲', label: 'Bermuda', code: '+1-441' },
  { flag: '🇧🇹', label: 'Bhutan', code: '+975' },
  { flag: '🇧🇴', label: 'Bolivia', code: '+591' },
  { flag: '🇧🇦', label: 'Bosnia & Herzegovina', code: '+387' },
  { flag: '🇧🇼', label: 'Botswana', code: '+267' },
  { flag: '🇧🇷', label: 'Brazil', code: '+55' },
  { flag: '🇻🇬', label: 'British Virgin Islands', code: '+1-284' },
  { flag: '🇧🇳', label: 'Brunei', code: '+673' },
  { flag: '🇧🇬', label: 'Bulgaria', code: '+359' },
  { flag: '🇧🇫', label: 'Burkina Faso', code: '+226' },
  { flag: '🇧🇮', label: 'Burundi', code: '+257' },

  { flag: '🇰🇭', label: 'Cambodia', code: '+855' },
  { flag: '🇨🇲', label: 'Cameroon', code: '+237' },
  { flag: '🇨🇦', label: 'Canada', code: '+1' },
  { flag: '🇨🇻', label: 'Cape Verde', code: '+238' },
  { flag: '🇰🇾', label: 'Cayman Islands', code: '+1-345' },
  { flag: '🇨🇫', label: 'Central African Republic', code: '+236' },
  { flag: '🇹🇩', label: 'Chad', code: '+235' },
  { flag: '🇨🇱', label: 'Chile', code: '+56' },
  { flag: '🇨🇳', label: 'China', code: '+86' },
  { flag: '🇨🇴', label: 'Colombia', code: '+57' },
  { flag: '🇰🇲', label: 'Comoros', code: '+269' },
  { flag: '🇨🇬', label: 'Congo', code: '+242' },
  { flag: '🇨🇩', label: 'Congo (DRC)', code: '+243' },
  { flag: '🇨🇷', label: 'Costa Rica', code: '+506' },
  { flag: '🇭🇷', label: 'Croatia', code: '+385' },
  { flag: '🇨🇺', label: 'Cuba', code: '+53' },
  { flag: '🇨🇾', label: 'Cyprus', code: '+357' },
  { flag: '🇨🇿', label: 'Czech Republic', code: '+420' },

  { flag: '🇩🇰', label: 'Denmark', code: '+45' },
  { flag: '🇩🇯', label: 'Djibouti', code: '+253' },
  { flag: '🇩🇲', label: 'Dominica', code: '+1-767' },
  { flag: '🇩🇴', label: 'Dominican Republic', code: '+1-809' },

  { flag: '🇪🇨', label: 'Ecuador', code: '+593' },
  { flag: '🇪🇬', label: 'Egypt', code: '+20' },
  { flag: '🇸🇻', label: 'El Salvador', code: '+503' },
  { flag: '🇬🇶', label: 'Equatorial Guinea', code: '+240' },
  { flag: '🇪🇷', label: 'Eritrea', code: '+291' },
  { flag: '🇪🇪', label: 'Estonia', code: '+372' },
  { flag: '🇸🇿', label: 'Eswatini', code: '+268' },
  { flag: '🇪🇹', label: 'Ethiopia', code: '+251' },

  { flag: '🇫🇯', label: 'Fiji', code: '+679' },
  { flag: '🇫🇮', label: 'Finland', code: '+358' },
  { flag: '🇫🇷', label: 'France', code: '+33' },

  { flag: '🇬🇦', label: 'Gabon', code: '+241' },
  { flag: '🇬🇲', label: 'Gambia', code: '+220' },
  { flag: '🇬🇪', label: 'Georgia', code: '+995' },
  { flag: '🇩🇪', label: 'Germany', code: '+49' },
  { flag: '🇬🇭', label: 'Ghana', code: '+233' },
  { flag: '🇬🇮', label: 'Gibraltar', code: '+350' },
  { flag: '🇬🇷', label: 'Greece', code: '+30' },
  { flag: '🇬🇱', label: 'Greenland', code: '+299' },
  { flag: '🇬🇩', label: 'Grenada', code: '+1-473' },
  { flag: '🇬🇺', label: 'Guam', code: '+1-671' },
  { flag: '🇬🇹', label: 'Guatemala', code: '+502' },
  { flag: '🇬🇬', label: 'Guernsey', code: '+44' },
  { flag: '🇬🇳', label: 'Guinea', code: '+224' },
  { flag: '🇬🇼', label: 'Guinea-Bissau', code: '+245' },

  { flag: '🇭🇹', label: 'Haiti', code: '+509' },
  { flag: '🇭🇳', label: 'Honduras', code: '+504' },
  { flag: '🇭🇰', label: 'Hong Kong', code: '+852' },
  { flag: '🇭🇺', label: 'Hungary', code: '+36' },

  { flag: '🇮🇸', label: 'Iceland', code: '+354' },
  { flag: '🇮🇳', label: 'India', code: '+91' },
  { flag: '🇮🇩', label: 'Indonesia', code: '+62' },
  { flag: '🇮🇷', label: 'Iran', code: '+98' },
  { flag: '🇮🇶', label: 'Iraq', code: '+964' },
  { flag: '🇮🇪', label: 'Ireland', code: '+353' },
  { flag: '🇮🇲', label: 'Isle of Man', code: '+44' },
  { flag: '🇮🇱', label: 'Israel', code: '+972' },
  { flag: '🇮🇹', label: 'Italy', code: '+39' },

  { flag: '🇯🇲', label: 'Jamaica', code: '+1-876' },
  { flag: '🇯🇵', label: 'Japan', code: '+81' },
  { flag: '🇯🇪', label: 'Jersey', code: '+44' },
  { flag: '🇯🇴', label: 'Jordan', code: '+962' },

  { flag: '🇰🇿', label: 'Kazakhstan', code: '+7' },
  { flag: '🇰🇪', label: 'Kenya', code: '+254' },
  { flag: '🇰🇼', label: 'Kuwait', code: '+965' },
  { flag: '🇰🇬', label: 'Kyrgyzstan', code: '+996' },

  { flag: '🇱🇦', label: 'Laos', code: '+856' },
  { flag: '🇱🇻', label: 'Latvia', code: '+371' },
  { flag: '🇱🇧', label: 'Lebanon', code: '+961' },
  { flag: '🇱🇸', label: 'Lesotho', code: '+266' },
  { flag: '🇱🇷', label: 'Liberia', code: '+231' },
  { flag: '🇱🇾', label: 'Libya', code: '+218' },
  { flag: '🇱🇮', label: 'Liechtenstein', code: '+423' },
  { flag: '🇱🇹', label: 'Lithuania', code: '+370' },
  { flag: '🇱🇺', label: 'Luxembourg', code: '+352' },

  { flag: '🇲🇴', label: 'Macau', code: '+853' },
  { flag: '🇲🇬', label: 'Madagascar', code: '+261' },
  { flag: '🇲🇼', label: 'Malawi', code: '+265' },
  { flag: '🇲🇾', label: 'Malaysia', code: '+60' },
  { flag: '🇲🇻', label: 'Maldives', code: '+960' },
  { flag: '🇲🇱', label: 'Mali', code: '+223' },
  { flag: '🇲🇹', label: 'Malta', code: '+356' },
  { flag: '🇲🇽', label: 'Mexico', code: '+52' },
  { flag: '🇲🇩', label: 'Moldova', code: '+373' },
  { flag: '🇲🇨', label: 'Monaco', code: '+377' },
  { flag: '🇲🇳', label: 'Mongolia', code: '+976' },
  { flag: '🇲🇪', label: 'Montenegro', code: '+382' },
  { flag: '🇲🇦', label: 'Morocco', code: '+212' },
  { flag: '🇲🇿', label: 'Mozambique', code: '+258' },
  { flag: '🇲🇲', label: 'Myanmar', code: '+95' },

  { flag: '🇳🇦', label: 'Namibia', code: '+264' },
  { flag: '🇳🇵', label: 'Nepal', code: '+977' },
  { flag: '🇳🇱', label: 'Netherlands', code: '+31' },
  { flag: '🇳🇿', label: 'New Zealand', code: '+64' },
  { flag: '🇳🇮', label: 'Nicaragua', code: '+505' },
  { flag: '🇳🇪', label: 'Niger', code: '+227' },
  { flag: '🇳🇬', label: 'Nigeria', code: '+234' },
  { flag: '🇰🇵', label: 'North Korea', code: '+850' },
  { flag: '🇲🇰', label: 'North Macedonia', code: '+389' },
  { flag: '🇳🇴', label: 'Norway', code: '+47' },

  { flag: '🇴🇲', label: 'Oman', code: '+968' },

  { flag: '🇵🇰', label: 'Pakistan', code: '+92' },
  { flag: '🇵🇦', label: 'Panama', code: '+507' },
  { flag: '🇵🇾', label: 'Paraguay', code: '+595' },
  { flag: '🇵🇪', label: 'Peru', code: '+51' },
  { flag: '🇵🇭', label: 'Philippines', code: '+63' },
  { flag: '🇵🇱', label: 'Poland', code: '+48' },
  { flag: '🇵🇹', label: 'Portugal', code: '+351' },

  { flag: '🇶🇦', label: 'Qatar', code: '+974' },

  { flag: '🇷🇴', label: 'Romania', code: '+40' },
  { flag: '🇷🇺', label: 'Russia', code: '+7' },

  { flag: '🇸🇦', label: 'Saudi Arabia', code: '+966' },
  { flag: '🇸🇳', label: 'Senegal', code: '+221' },
  { flag: '🇷🇸', label: 'Serbia', code: '+381' },
  { flag: '🇸🇬', label: 'Singapore', code: '+65' },
  { flag: '🇸🇰', label: 'Slovakia', code: '+421' },
  { flag: '🇸🇮', label: 'Slovenia', code: '+386' },
  { flag: '🇿🇦', label: 'South Africa', code: '+27' },
  { flag: '🇰🇷', label: 'South Korea', code: '+82' },
  { flag: '🇪🇸', label: 'Spain', code: '+34' },
  { flag: '🇱🇰', label: 'Sri Lanka', code: '+94' },
  { flag: '🇸🇪', label: 'Sweden', code: '+46' },
  { flag: '🇨🇭', label: 'Switzerland', code: '+41' },

  { flag: '🇹🇼', label: 'Taiwan', code: '+886' },
  { flag: '🇹🇭', label: 'Thailand', code: '+66' },
  { flag: '🇹🇳', label: 'Tunisia', code: '+216' },
  { flag: '🇹🇷', label: 'Turkey', code: '+90' },

  { flag: '🇺🇦', label: 'Ukraine', code: '+380' },
  { flag: '🇦🇪', label: 'United Arab Emirates', code: '+971' },
  { flag: '🇬🇧', label: 'United Kingdom', code: '+44' },
  { flag: '🇺🇸', label: 'United States', code: '+1' },
  { flag: '🇺🇾', label: 'Uruguay', code: '+598' },
  { flag: '🇺🇿', label: 'Uzbekistan', code: '+998' },

  { flag: '🇻🇪', label: 'Venezuela', code: '+58' },
  { flag: '🇻🇳', label: 'Vietnam', code: '+84' },

  { flag: '🇾🇪', label: 'Yemen', code: '+967' },

  { flag: '🇿🇲', label: 'Zambia', code: '+260' },
  { flag: '🇿🇼', label: 'Zimbabwe', code: '+263' },
];