import type { CSSProperties } from 'react';

type StyleValue = CSSProperties | ((...args: any[]) => CSSProperties);

const S: Record<string, StyleValue> = {
  app: {
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    background: '#111111',
    color: '#F1F0ED',
    minHeight: '100dvh',
    maxWidth: '430px',
    margin: '0 auto',
    position: 'relative',
    paddingBottom: '80px',
  },
  topbar: {
    background: '#1A1A1A',
    borderBottom: '1px solid #2A2A2A',
    padding: '14px 16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'sticky',
    top: 0,
    zIndex: 50,
  },
  topbarTitle: {
    fontSize: '17px',
    fontWeight: 600,
    color: '#F1F0ED',
    margin: 0,
  },
  topbarSub: {
    fontSize: '12px',
    color: '#888',
    margin: 0,
    marginTop: 1,
  },
  liveChip: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    background: 'rgba(34,197,94,0.12)',
    border: '1px solid rgba(34,197,94,0.3)',
    borderRadius: '20px',
    padding: '4px 10px',
    fontSize: '11px',
    fontWeight: 600,
    color: '#22C55E',
    letterSpacing: '0.3px',
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: '50%',
    background: '#22C55E',
    animation: 'pulse 2s infinite',
  },
  navBar: {
    position: 'fixed',
    bottom: 0,
    left: '50%',
    transform: 'translateX(-50%)',
    width: '100%',
    maxWidth: '430px',
    background: '#1A1A1A',
    borderTop: '1px solid #2A2A2A',
    display: 'flex',
    padding: '8px 0 12px',
    zIndex: 100,
  },
  navItem: (active: boolean) => ({
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 3,
    padding: '4px 0',
    border: 'none',
    background: 'transparent',
    color: active ? '#FF6B2B' : '#555',
    cursor: 'pointer',
    transition: 'color 0.15s',
    fontSize: '10px',
    fontWeight: active ? 600 : 400,
  }),
  section: {
    padding: '16px',
  },
  card: {
    background: '#1E1E1E',
    border: '1px solid #2A2A2A',
    borderRadius: '14px',
    padding: '14px',
    marginBottom: '10px',
  },
  metricGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '10px',
    marginBottom: '16px',
  },
  metricCard: (accent: string) => ({
    background: '#1E1E1E',
    border: `1px solid ${accent ? accent + '30' : '#2A2A2A'}`,
    borderRadius: '14px',
    padding: '14px',
    borderLeft: accent ? `3px solid ${accent}` : '1px solid #2A2A2A',
  }),
  metricLabel: {
    fontSize: '11px',
    color: '#666',
    marginBottom: '4px',
    fontWeight: 500,
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  metricValue: {
    fontSize: '24px',
    fontWeight: 700,
    color: '#F1F0ED',
    lineHeight: 1,
  },
  metricSub: {
    fontSize: '11px',
    color: '#555',
    marginTop: '3px',
  },
  orderCard: (status: string) => ({
    background: '#1E1E1E',
    border: '1px solid #2A2A2A',
    borderRadius: '14px',
    overflow: 'hidden',
    marginBottom: '10px',
    borderLeft: `4px solid ${status ? '#555' : '#555'}`,
  }),
  orderCardInner: {
    padding: '14px',
  },
  orderHead: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: '8px',
  },
  orderId: {
    fontSize: '18px',
    fontWeight: 800,
    color: '#FF6B2B',
    lineHeight: 1,
  },
  orderName: {
    fontSize: '14px',
    fontWeight: 600,
    color: '#F1F0ED',
    marginTop: '2px',
  },
  statusBadge: (status: string) => ({
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    padding: '3px 9px',
    borderRadius: '20px',
    fontSize: '11px',
    fontWeight: 600,
    background: '#333',
    color: '#aaa',
    whiteSpace: 'nowrap',
  }),
  timeBadge: {
    display: 'inline-block',
    padding: '2px 7px',
    background: '#2A2A2A',
    borderRadius: '20px',
    fontSize: '11px',
    color: '#888',
    marginTop: '4px',
  },
  locationRow: {
    display: 'flex',
    gap: '6px',
    alignItems: 'flex-start',
    color: '#888',
    fontSize: '12px',
    marginBottom: '4px',
    lineHeight: 1.4,
  },
  itemRow: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '13px',
    color: '#CCC',
    marginBottom: '4px',
  },
  divider: {
    height: 1,
    background: '#2A2A2A',
    margin: '10px 0',
  },
  totalRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '8px',
  },
  totalAmount: {
    fontSize: '18px',
    fontWeight: 700,
    color: '#F1F0ED',
  },
  payBadge: (paid: boolean) => ({
    display: 'inline-block',
    padding: '3px 9px',
    borderRadius: '20px',
    fontSize: '11px',
    fontWeight: 600,
    background: paid ? 'rgba(34,197,94,0.12)' : 'rgba(239,68,68,0.12)',
    color: paid ? '#22C55E' : '#EF4444',
  }),
  actionRow: {
    display: 'flex',
    gap: '8px',
    marginTop: '12px',
  },
  btnPrimary: (color: string) => ({
    flex: 1,
    padding: '11px',
    borderRadius: '10px',
    border: 'none',
    background: color || '#FF6B2B',
    color: '#fff',
    fontWeight: 700,
    fontSize: '13px',
    cursor: 'pointer',
    letterSpacing: '0.2px',
  }),
  btnSecondary: {
    padding: '11px 14px',
    borderRadius: '10px',
    border: '1px solid #2A2A2A',
    background: 'transparent',
    color: '#888',
    fontWeight: 600,
    fontSize: '13px',
    cursor: 'pointer',
  },
  btnDanger: {
    padding: '11px 14px',
    borderRadius: '10px',
    border: '1px solid rgba(239,68,68,0.3)',
    background: 'rgba(239,68,68,0.1)',
    color: '#EF4444',
    fontWeight: 600,
    fontSize: '13px',
    cursor: 'pointer',
  },
  sectionTitle: {
    fontSize: '13px',
    fontWeight: 600,
    color: '#666',
    textTransform: 'uppercase',
    letterSpacing: '0.8px',
    marginBottom: '12px',
    marginTop: '4px',
  },
  filterRow: {
    display: 'flex',
    gap: '8px',
    marginBottom: '14px',
    overflowX: 'auto',
    paddingBottom: '4px',
  },
  filterChip: (active: boolean) => ({
    padding: '6px 14px',
    borderRadius: '20px',
    border: active ? 'none' : '1px solid #2A2A2A',
    background: active ? '#FF6B2B' : '#1E1E1E',
    color: active ? '#fff' : '#888',
    fontSize: '12px',
    fontWeight: 600,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    transition: 'all 0.15s',
  }),
  productRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 0',
    borderBottom: '1px solid #222',
  },
  productEmoji: {
    width: 40,
    height: 40,
    borderRadius: '10px',
    background: '#2A2A2A',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '18px',
    flexShrink: 0,
  },
  productName: {
    fontSize: '14px',
    fontWeight: 600,
    color: '#F1F0ED',
    marginBottom: '2px',
  },
  productMeta: {
    fontSize: '12px',
    color: '#666',
  },
  stockBadge: (stock: number) => ({
    display: 'inline-block',
    padding: '2px 8px',
    borderRadius: '6px',
    fontSize: '12px',
    fontWeight: 700,
    background: stock > 10 ? 'rgba(34,197,94,0.1)' : stock > 0 ? 'rgba(245,158,11,0.1)' : 'rgba(239,68,68,0.1)',
    color: stock > 10 ? '#22C55E' : stock > 0 ? '#F59E0B' : '#EF4444',
  }),
  toggleSwitch: (active: boolean) => ({
    width: 36,
    height: 20,
    borderRadius: '10px',
    background: active ? '#FF6B2B' : '#333',
    position: 'relative',
    cursor: 'pointer',
    transition: 'background 0.2s',
    flexShrink: 0,
    border: 'none',
  }),
  toggleKnob: (active: boolean) => ({
    position: 'absolute',
    top: 2,
    left: active ? 18 : 2,
    width: 16,
    height: 16,
    borderRadius: '50%',
    background: '#fff',
    transition: 'left 0.2s',
  }),
  barChart: {
    display: 'flex',
    alignItems: 'flex-end',
    gap: '6px',
    height: '80px',
    marginTop: '8px',
  },
  barCol: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '4px',
  },
  bar: (pct: number, isToday: boolean) => ({
    width: '100%',
    height: `${pct}%`,
    background: isToday ? '#FF6B2B' : '#2A2A2A',
    borderRadius: '4px 4px 0 0',
    transition: 'height 0.3s',
    minHeight: 4,
  }),
  barLabel: {
    fontSize: '10px',
    color: '#555',
  },
  topProductRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '10px',
  },
  topProductRank: {
    width: 22,
    height: 22,
    borderRadius: '6px',
    background: '#2A2A2A',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '11px',
    fontWeight: 700,
    color: '#666',
    flexShrink: 0,
  },
  progressBar: (pct?: number) => ({
    height: 4,
    borderRadius: 2,
    background: '#2A2A2A',
    marginTop: 4,
    overflow: 'hidden',
  }),
  progressFill: (pct: number) => ({
    height: '100%',
    width: `${pct}%`,
    background: '#FF6B2B',
    borderRadius: 2,
  }),
  operatorCard: {
    background: '#1E1E1E',
    border: '1px solid #2A2A2A',
    borderRadius: '16px',
    padding: '18px',
    marginBottom: '12px',
  },
  opOrderId: {
    fontSize: '13px',
    fontWeight: 700,
    color: '#FF6B2B',
    marginBottom: '4px',
    letterSpacing: '0.5px',
  },
  opName: {
    fontSize: '22px',
    fontWeight: 800,
    color: '#F1F0ED',
    marginBottom: '8px',
  },
  opLocation: {
    fontSize: '13px',
    color: '#888',
    marginBottom: '12px',
    display: 'flex',
    alignItems: 'flex-start',
    gap: '5px',
  },
  opItems: {
    background: '#151515',
    borderRadius: '10px',
    padding: '10px 12px',
    marginBottom: '12px',
  },
  opItem: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '14px',
    color: '#CCC',
    marginBottom: '5px',
  },
  opTotal: {
    fontSize: '26px',
    fontWeight: 800,
    color: '#F1F0ED',
  },
  opBtn: (color: string) => ({
    width: '100%',
    padding: '16px',
    borderRadius: '12px',
    border: 'none',
    background: color,
    color: '#fff',
    fontWeight: 800,
    fontSize: '16px',
    cursor: 'pointer',
    letterSpacing: '0.5px',
    marginTop: '10px',
  }),
  emptyState: {
    textAlign: 'center',
    padding: '48px 24px',
    color: '#444',
  },
  emptyIcon: {
    fontSize: '40px',
    marginBottom: '12px',
  },
  emptyTitle: {
    fontSize: '16px',
    fontWeight: 600,
    color: '#555',
    marginBottom: '6px',
  },
  emptyText: {
    fontSize: '13px',
    color: '#444',
    lineHeight: 1.6,
  },
  notesBox: {
    background: 'rgba(245,158,11,0.08)',
    border: '1px solid rgba(245,158,11,0.2)',
    borderRadius: '8px',
    padding: '8px 10px',
    fontSize: '12px',
    color: '#F59E0B',
    display: 'flex',
    gap: '6px',
    alignItems: 'flex-start',
    marginBottom: '8px',
  },
  input: {
    width: '100%',
    background: '#151515',
    border: '1px solid #2A2A2A',
    borderRadius: '10px',
    padding: '11px 14px',
    fontSize: '14px',
    color: '#F1F0ED',
    outline: 'none',
    boxSizing: 'border-box',
    marginBottom: '10px',
  },
};

export default S;
